//==============================================================================
// Project : I2C Master Controller
// File    : i2c_shift_reg.sv
// Author  : Sarathi Selvam D
//
// Description:
// Implements the transmit (TX) and receive (RX) shift registers for the
// I2C Master.
//
// TX Path
// --------
// - Parallel load of Address+R/W or TX data
// - MSB-first serial transmission
//
// RX Path
// --------
// - Serial reception from SDA
// - MSB-first shifting
// - Parallel output after one byte
//
// Note:
// tx_shift and rx_shift are expected to be ONE-CLOCK PULSES generated by the
// Timing Engine.
//==============================================================================

import i2c_pkg::*;

module i2c_shift_reg(
	
	input logic clk,
	input logic rst_n,
	
	input logic tx_load,
	input logic tx_shift,
	input logic [DATA_WIDTH-1:0] tx_data,
	
	input logic rx_shift,
	input logic serial_in,
	
	output logic serial_out,
	output logic [DATA_WIDTH-1:0] rx_data
);

	logic [DATA_WIDTH-1:0] tx_shift_reg;
	logic [DATA_WIDTH-1:0] rx_shift_reg;
	
	always_ff @(posedge clk or negedge rst_n) begin
	
		if(!rst_n) begin
			tx_shift_reg <= '0;
		end
		
		else begin
			if(tx_load)
				tx_shift_reg <= tx_data;
			else if(tx_shift)
				tx_shift_reg <= {tx_shift_reg[DATA_WIDTH-2:0],1'b0};
		end
	
	end
	
	always_ff @(posedge clk or negedge rst_n) begin
	
		if(!rst_n) begin
			rx_shift_reg <= '0;
		end
		
		else begin
			if(rx_shift)
				rx_shift_reg <= {rx_shift_reg[DATA_WIDTH-2:0],serial_in};
		end
	
	end
	
	assign serial_out = tx_shift_reg[DATA_WIDTH-1];
	
	assign rx_data = rx_shift_reg;
	
endmodule
